site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition

extra_javascript:
  - js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
